name: Update exchange rates

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci

      - name: Create .env file
        run: |
          echo EXCHANGE_API_KEY=${{ secrets.EXCHANGE_API_KEY }} >> .env
          echo BASE_CURRENCIES=${{ vars.BASE_CURRENCIES }} >> .env
      
      - name: Run exchange rate generator
        run: npm run build:exchange-rates
      
      - name: Remove .env file
        run: rm -f .env

      - name: Commit and push updated exchange rate data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/exchange-rates
          git diff --quiet || git commit -m "chore: update exchange rate data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
